name: Unit and Coverage test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - name: Checkout with all submodules
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Get Ruby v3 with bundler cache
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.2.1' # Not needed with a .ruby-version file
          bundler-cache: true
          cache-version: 1
      - name: Run unit test script
        run: |
          bashcov unit-test.sh
      - name: Upload reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      - name: Clean files
        run: |
          rm -rf vendor
          rm -rf Gemfile.lock
      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Push coverage report
          file_pattern: 'coverage/**'
          commit_user_name: jmrplens
          commit_user_email: jmrplens@gmail.com
